### ISSUE TITLE
Throwing Error:  'The website encountered an unexpected error. Please try again later.'

### ISSUE THREAD

**Issue by rakeshjames** [stratus-meridian/sm_appdashboard_apigee#2]
# Steps to reproduce

1. Fresh installation of SM Dev portal with sm_appdashboard_apigee module
2. Then going to `admin/config/apigee-edge/apps-dashboard` or  Configuration >> Apigee Edge >> Apps Dashboard , giving the 
<img width="745" alt="Screenshot 2020-05-02 at 2 31 04 AM" src="https://user-images.githubusercontent.com/3348273/80852135-0c361580-8c1e-11ea-941c-43134bb32b0f.png">
following error
When I looked at the log, which gives 
<img width="1273" alt="Screenshot 2020-05-02 at 2 31 16 AM" src="https://user-images.githubusercontent.com/3348273/80852157-49020c80-8c1e-11ea-83a6-3b61ec9dcd08.png">

**Comment by kiranjyoth** [comment]
Fixed with #4
