### ISSUE TITLE
Add DI to AppsDashboardStorage class also consider to make that as service class.

### ISSUE THREAD

**Issue by rakeshjames** [stratus-meridian/sm_appdashboard_apigee#3]
# Tasks

- Add Dependency Injections to AppsDashboardStorage class
-  Change AppsDashboardStorage class into a Service

**Comment by mergrita24** [comment]
Hello @rakeshjames ,

Good day. 

I had now merged your code to master branch. Let me start the doing sanity test as well in parallel to the enhancement currently being donel; for which I am adding a search function on it.

thank you.

Kind Regards,
Mer
